housepee_asp/housepee_asp/Areas/Admin/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using housepee_asp.Models;

namespace housepee_asp.Areas.Admin.Controllers
{
    public class BlogsController : Controller
    {
        private HousepeeDBContext db = new HousepeeDBContext();

        // GET: Admin/Blogs
        public ActionResult Index()
        {
            var blogs = db.blogs.Include(b => b.user);
            return View(blogs.ToList());
        }

        // GET: Admin/Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blogs blogs = db.blogs.Find(id);
            if (blogs == null)
            {
                return HttpNotFound();
            }
            return View(blogs);
        }

        // GET: Admin/Blogs/Create
        public ActionResult Create()
        {
            ViewBag.user_id = new SelectList(db.user, "user_id", "password");
            return View();
        }

        // POST: Admin/Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "blog_id,title,content,image,createTime,user_id")] blogs blogs)
        {
            if (ModelState.IsValid)
            {
                db.blogs.Add(blogs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.user_id = new SelectList(db.user, "user_id", "password", blogs.user_id);
            return View(blogs);
        }

        // GET: Admin/Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blogs blogs = db.blogs.Find(id);
            if (blogs == null)
            {
                return HttpNotFound();
            }
            ViewBag.user_id = new SelectList(db.user, "user_id", "password", blogs.user_id);
            return View(blogs);
        }

        // POST: Admin/Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "blog_id,title,content,image,createTime,user_id")] blogs blogs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.user_id = new SelectList(db.user, "user_id", "password", blogs.user_id);
            return View(blogs);
        }

        // GET: Admin/Blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blogs blogs = db.blogs.Find(id);
            if (blogs == null)
            {
                return HttpNotFound();
            }
            return View(blogs);
        }

        // POST: Admin/Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            blogs blogs = db.blogs.Find(id);
            db.blogs.Remove(blogs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

housepee_asp/housepee_asp/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using housepee_asp.Models;

namespace housepee_asp.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
        private HousepeeDBContext db = new HousepeeDBContext();

        // GET: Admin/Users
        public ActionResult Index()
        {
            return View(db.user.ToList());
        }

        // GET: Admin/Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user_id,password,name_user,location,email,phonenumber,isadmin,blog_id,avatar")] user user)
        {
            if (ModelState.IsValid)
            {
                db.user.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Admin/Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user_id,password,name_user,location,email,phonenumber,isadmin,blog_id,avatar")] user user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Admin/Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            user user = db.user.Find(id);
            db.user.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

housepee_asp/housepee_asp/Controllers/RoomDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using housepee_asp.Models;
using housepee_asp.ViewModel;
using housepee_asp.Services;
using Newtonsoft.Json;
using System.IO;

namespace housepee_asp.Controllers
{
    public class RoomDetailController : Controller
    {
        private HousepeeDBContext db = new HousepeeDBContext();

        // GET: RoomDetail
        public ActionResult Index()
        {
            ViewBag.CityList = new SelectList(db.tinhthanhpho, "matp", "name");
            ViewBag.DistrictList = new SelectList(db.quanhuyen, "maqh", "name");
            ViewBag.SubDistrictList = new SelectList(db.xaphuongthitran, "xaid", "name");
            ViewBag.StreetList = new SelectList(db.duong, "maduong", "name");
            var model = new RoomService().ListRoomImage();
            //Distint list
            var newmodel = new RoomService().DistinctList(model);
            //End distint list
            return View(newmodel);
        }

        // GET: RoomDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = new RoomImageService().RoomImageDetailById(id);
            //var model2 = new RoomService().RoomTypeById(id);
            //RoomDetailViewModel roomDetailViewModel = db.RoomDetailViewModels.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }



        public ActionResult Search(string city, string distric, string sub_distric, string street, int? up, int? down)
        {


            var model = (from a in db.roomdetail.AsEnumerable()
                         join b in db.roomimages.AsEnumerable().DefaultIfEmpty()
                            on a.room_id equals b.room_id
                         join c in db.roomtype.AsEnumerable() on a.room_type_id equals c.room_type_id
                         join d in db.user on a.user_id equals d.user_id
                         select new RoomDetailViewModel()
                         {
                             id = a.room_id,
                             image = b.url,
                             title = a.name,
                             city = a.city,
                             sub_distric = a.sub_distric,
                             distric = a.distric,
                             street = a.street,
                             number = a.number,
                             price_room = a.price_room,
                             area = a.area,
                             createTime = a.createTime,
                             toilet = a.toilet,
                             Name_user = d.name_user,
                             name_type_room = c.name_type_room,

                         }).ToList();
            if (city.Length > 0)
            {
                model.Where(x => x.city == city).ToList();
                if (distric.Length > 0)
                {
                    model.Where(x => x.distric == distric).ToList();
                    if (sub_distric.Length > 0)
                    {
                        model.Where(x => x.sub_distric == sub_distric).ToList();
                    }
                    if (street.Length > 0)
                    {
                        model.Where(x => x.street == street).ToList();
                        if (up != null && down == null)
                        {
                            model.Where(x => x.price_room > up).ToList();
                        }
                        if (down != null && up == null)
                        {
                            model.Where(x => x.price_room > down).ToList();
                        }
                        if (down != null && up != null)
                        {
                            model.Where(x => x.price_room > down && x.price_room > up).ToList();
                        }
                    }
                }
            }

            //Distint list
            var newmodel = new RoomService().DistinctList(model);
            //End distint list

            return View("Index", newmodel);
        }

        public ActionResult Create()
        {
            if (Session["UserId"] != null)
            {
                ViewBag.room_type_id = new SelectList(db.roomtype, "room_type_id", "name_type_room");
                return View();
            }

            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: RoomDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomDetailViewModelForUpLoad roomDetailViewModel)
        {
            if (ModelState.IsValid)
            {
                roomdetail inputRoomDetail = new roomdetail();
                inputRoomDetail.price_room = roomDetailViewModel.price_room;
                inputRoomDetail.price_water = roomDetailViewModel.price_water;
                inputRoomDetail.price_electric = roomDetailViewModel.price_electric;
                inputRoomDetail.name = roomDetailViewModel.title;
                inputRoomDetail.description = roomDetailViewModel.description;
                inputRoomDetail.area = Convert.ToInt32(roomDetailViewModel.area);
                inputRoomDetail.services = roomDetailViewModel.services;
                inputRoomDetail.createTime = DateTime.Now;
                inputRoomDetail.room_type_id = roomDetailViewModel.room_type_id;
                inputRoomDetail.toilet = roomDetailViewModel.toilet;
                inputRoomDetail.bedroom = roomDetailViewModel.bedroom;
                inputRoomDetail.distric = roomDetailViewModel.distric;
                inputRoomDetail.number = roomDetailViewModel.number;
                inputRoomDetail.createBy = Session["Username"].ToString();
                inputRoomDetail.sub_distric = roomDetailViewModel.sub_distric;
                inputRoomDetail.city = roomDetailViewModel.city;
                inputRoomDetail.street = roomDetailViewModel.street;
                inputRoomDetail.user_id = Convert.ToInt32(Session["UserId"]);
                db.roomdetail.Add(inputRoomDetail);
                db.SaveChanges();
                var idInputRoomDetail = inputRoomDetail.room_id;
                if (roomDetailViewModel.File != null && roomDetailViewModel.File.ContentLength > 0)
                    try
                    {
                        string path2 = Server.MapPath("~/images/users/" + Session["UserId"]);
                        if (!System.IO.Directory.Exists(path2))
                        {
                            Directory.CreateDirectory(path2);

                        }
                        string path = Path.Combine(Server.MapPath("~/images/users/" + Session["UserId"]),
                                                   Path.GetFileName(roomDetailViewModel.File.FileName));
                        roomDetailViewModel.File.SaveAs(path);
                        //Save url images in database
                        roomimages input = new roomimages();
                        input.url = "/images/users/" + Session["UserId"] + "/" + roomDetailViewModel.File.FileName;
                        input.room_id = idInputRoomDetail;
                        db.roomimages.Add(input);
                        db.SaveChanges();
                        ViewBag.Message = "File uploaded successfully";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
                    ViewBag.Message = "You have not specified a file.";
                }

                return RedirectToAction("Index");
            }
            //ViewBag.room_type_id = new SelectList(db.roomtype, "room_type_id", "name_type_room", roomDetailViewModel.room_type_id);
            return View(roomDetailViewModel);
        }
        // GET: RoomDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = new RoomService().ListRoomImageById(id);
            //RoomDetailViewModel roomDetailViewModel = db.RoomDetailViewModels.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: RoomDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,image,description,services,price_room,price_water,price_electric,toilet,bedroom,title,city,sub_distric,distric,street,number,area,createTime,lastModifieldBy,lastModifieldTime,room_type_id,user_id")] RoomDetailViewModel roomDetailViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomDetailViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roomDetailViewModel);
        }

        // GET: RoomDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

housepee_asp/housepee_asp/Views/Users/BlogList.cshtml
@model IEnumerable<housepee_asp.Models.blogs>
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}

<
<style>
    /*.text-truncate {
        white-space: nowrap !important;
        overflow: hidden !important;
        text-overflow: ellipsis !important;
        width:100%!important;
    }*/
</style>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Danh sách bài viết</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <p>
                @Html.ActionLink("Create New", "Create","Blogs")
            </p>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th class="column-title">Mã bài viết </th>
                                <th class="column-title">Tên bài viết </th>
                                <th class="column-title">Ngày tạo </th>
                                <th class="column-title">Mã người viết</th>
                                <th class="column-title">Tên người viết</th>
                                <th class="column-title no-link last">
                                    <span class="nobr">Thao tác</span>
                                </th>

                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="even pointer">
                                    <td class=" ">@Html.DisplayFor(modelItem => item.blog_id)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.title)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.createTime)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.user_id) </td>
                                    <td class="text-truncate">@Html.DisplayFor(modelItem => item.user.username)</td>
                                    <td class="last">
                                        @Html.ActionLink("Edit", "Edit","Blogs", new { id = item.blog_id },null) |
                                        @Html.ActionLink("Details", "Details", "Blogs", new { id = item.blog_id },null) |
                                        @Html.ActionLink("Delete", "Delete", "Blogs", new { id = item.blog_id },null)
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>

housepee_asp/housepee_asp/Views/Users/ChangePassWord.cshtml
@{
    ViewBag.Title = "ChangePassWord";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@using (Html.BeginForm("ChangePassWord","Users",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <form>
        <div class="form-group">
            <h2>@ViewBag.Mess</h2>
            <label for="exampleInputEmail1">Mật khẩu cũ</label>
            <input type="password" class="form-control" name="password" placeholder="Mật khẩu cũ">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Mật khẩu mới</label>
            <input type="password" class="form-control" id="password" onchange='check_pass();' placeholder="Mật khẩu mới">
            <label for="exampleInputPassword1">Xác nhận mật khẩu</label>
            <input type="password" class="form-control" id="confirm_password" name="newPassword" onchange='check_pass();' placeholder="Xác nhận mật khẩu mới">
        </div>
        <span id='message'></span>
        <input type="submit" name="submit" value="Đổi mật khẩu" id="submit" disabled />
    </form>
}
    <script>
          
        function check_pass() {
            if (document.getElementById('password').value ==
                document.getElementById('confirm_password').value) {
                document.getElementById('submit').disabled = false;
            } else {
                document.getElementById('submit').disabled = true;
            }
        }
    </script>

housepee_asp/housepee_asp/Views/Users/Details.cshtml
@model housepee_asp.Models.user

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Thông tin người dùng</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Tên người dùng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_user)
        </dd>

        <dt>
            Tên đăng nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
Số điện thoại        </dt>

        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>

   

 

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa thông tin cá nhân", "Edit", new { id = Model.user_id }) |
    @Html.ActionLink("Đổi mật khẩu", "ChangePassWord","Users")
</p>

housepee_asp/housepee_asp/Views/Users/Invoice.cshtml
@model IEnumerable<housepee_asp.Models.invoice>
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@Html.ActionLink("Create New", "Create")
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Danh sách phòng</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th class="column-title">Mã phòng </th>
                                <th class="column-title">Tên phòng</th>
                                <th class="column-title">Ngày tạo </th>
                                <th class="column-title">Giá phòng</th>
                                <th class="column-title no-link last">
                                    <span class="nobr">Thao tác</span>
                                </th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr class="even pointer">
                                    <td class=" ">@Html.DisplayFor(modelItem => item.room_id)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.roomdetail.name)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.roomdetail.createTime) </td>
                                    <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.roomdetail.price_room)</td>
                                    <td class=" last">
                                        @Html.ActionLink("Details", "Details","RoomDetail", new { id = item.id }, null) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>

housepee_asp/housepee_asp/Views/Users/RoomDetail.cshtml
@model IEnumerable<housepee_asp.ViewModel.RoomDetailViewModel>

@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}



@Html.ActionLink("Create New", "Create","Roomdetail")
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Danh sách phòng</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="#">Settings 1</a>
                            </li>
                            <li>
                                <a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th class="column-title">Mã phòng </th>
                                <th class="column-title">Tên phòng</th>
                                <th class="column-title">Ngày tạo </th>
                                <th class="column-title">Loại Phòng</th>
                                <th class="column-title">Người tạo</th>
                                <th class="column-title">Giá phòng</th>
                                <th class="column-title no-link last">
                                    <span class="nobr">Thao tác</span>
                                </th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr class="even pointer">
                                    <td class=" ">@Html.DisplayFor(modelItem => item.id)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.title)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.createTime) </td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.name_type_room)</td>
                                    <td class=" ">@Html.DisplayFor(modelItem => item.Name_user)</td>
                                    <td class="a-right a-right ">@Html.DisplayFor(modelItem => item.price_room)</td>
                                    <td class=" last">
                                        @Html.ActionLink("Edit", "Edit", "RoomDetail", new { id = item.id },null) |
                                        @Html.ActionLink("Details", "Details", "RoomDetail", new { id = item.id },null) |
                                        @Html.ActionLink("Delete", "Delete", "RoomDetail", new { id = item.id },null)
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>